# Site settings
title: Colloque Tsui
email: colloquet@gmail.com
description: "Colloque Tsui's blog"
baseurl: "/"
url: "http://colloque.me"
paginate: 6
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
